trigger: 
  - releases/*
  - main

variables:
  - group: terraform-environments

pool:
  vmImage: ubuntu-latest

stages:
- stage: publish_artefact
  displayName: 'Publish terraform files'
  jobs:
    - job:
      steps:
        - task: CmdLine@2
          inputs:
            script: 'ls'
        - task: CopyFiles@2
          inputs:
            SourceFolder: 'src'
            Contents: '**'
            TargetFolder: '$(System.ArtifactsDirectory)/terraform'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'