trigger: 
  - releases/*
  - main

variables:
  - group: terraform-environments

pool:
  vmImage: ubuntu-latest

stages:
- stage: terraform_validate
  displayName: Install terraform and validate code
  jobs: 
   - job: 
     continueOnError: false
     steps:
       - task: TerraformInstaller@0
         displayName: Install Terraform
         inputs:
           terraformVersion: latest
       - task: TerraformTaskV4@4
         inputs:
           provider: 'azurerm'
           command: 'init'
           backendServiceArm: 'Visual Studio Professional Subscription (d47d357f-a6d6-4ed4-aaaa-e691f75b278e)'
           backendAzureRmResourceGroupName: 'terraform-backend-rg'
           backendAzureRmStorageAccountName: 'eshopterraformbackendsa'
           backendAzureRmContainerName: 'terraform-state-dev1-container'
           backendAzureRmKey: 'none'
       - task: TerraformTaskV4@4
         inputs:
          provider: 'azurerm'
          command: 'validate'
      
     
    