trigger: none

variables:
  - group: terraform-environments

pool:
  vmImage: ubuntu-latest

stages:
- stage: terraform_install
  displayName: Install terraform and validate code
  jobs: 
   - job: 
     continueOnError: false
     steps:
       - task: TerraformInstaller@0
         displayName: Install Terraform
         inputs:
           terraformVersion: latest

- stage: terraform_deploy
  displayName: terraform validate code and deploy
  jobs: 
   - job: 
     continueOnError: false
     steps:
       - task: ManualValidation@0
         inputs: 
           instructions: 'dev1'
     
    