trigger: none

variables:
  - group: terraform-environments

pool:
  vmImage: ubuntu-latest

stages:
- stage: terraform_install
  displayName: Install terraform and validate code
  jobs: 
   - job: 
     continueOnError: false
     steps:
       - task: TerraformInstaller@0
         displayName: Install Terraform
         inputs:
           terraformVersion: latest

- stage: terraform_deploy
  displayName: terraform validate code and deploy
  jobs:  
   - job: dev1-deploy
     displayName: 'dev1-deploy'
     pool: server
     continueOnError: false
     steps:
       - task: ManualValidation@0
         inputs: 
           notifyUsers:
           instructions: 'are you sure you want to deplou to dev1?'
           onTimeout: 'reject'
   - job: echo 
     displayName: echo
     dependsOn: dev1-deploy
     steps:
       - task: CmdLine@2
         inputs:
          script: echo Hello world
     
    