trigger: 
  - releases/*

variables:
  - group: terraform-environments

pool:
  vmImage: ubuntu-latest

stages:
- stage: terraform_install
  displayName: Install terraform and validate code
  jobs: 
   - job: 
     continueOnError: false
     steps:
       - task: TerraformInstaller@0
         displayName: Install Terraform
         inputs:
           terraformVersion: latest

- stage: terraform_deploy
  displayName: terraform validate code and deploy
  jobs:  
    - job: dev1_deploy
      displayName: 'dev1-deploy'
      pool: server
      continueOnError: false
      steps:
        - task: ManualValidation@0
          inputs: 
            notifyUsers:
            instructions: 'are you sure you want to deplou to dev1?'
            onTimeout: 'reject'
    - job: dev2_deploy
      displayName: 'dev1-deploy'
      pool: server
      continueOnError: false
      steps:
       - task: ManualValidation@0
         inputs: 
           notifyUsers:
           instructions: 'are you sure you want to deplou to dev1?'
           onTimeout: 'reject'
    - job: stage_deploy
      displayName: 'dev1-deploy'
      pool: server
      continueOnError: false
      steps:
       - task: ManualValidation@0
         inputs: 
           notifyUsers:
           instructions: 'are you sure you want to deplou to dev1?'
           onTimeout: 'reject'
    - job: production_deploy
      displayName: 'dev1-deploy'
      pool: server
      continueOnError: false
      steps:
       - task: ManualValidation@0
         inputs: 
           notifyUsers:
           instructions: 'are you sure you want to deplou to dev1?'
           onTimeout: 'reject'
    
    - job: echo 
      displayName: echo
      dependsOn: dev1_deploy
      steps:
       - task: CmdLine@2
         inputs:
          script: echo Hello world from dev1